### PR TITLE
fix(Preset): resolve undetected date-state classes animations

### LINKED ISSUE #474: fix: broken animations
### Description

When using UnoCSS `shortcuts` to apply animations, and then attempting to override animation-related CSS variables via additional modifiers, the overrides are **not respected**. As a result, the animation is either broken or completely missing.

---

### 🔁 Reproduction

We define the following shortcut:

```ts
export const staticPopover: Record<`${PopoverPrefix}-${string}`, string> = {
  'popover-content': 'z-50 w-72 rounded-md border border-base bg-popover p-4 text-popover shadow-md outline-none data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[side=bottom]:slide-in-from-top-2 data-[side=left]:slide-in-from-right-2 data-[side=right]:slide-in-from-left-2 data-[side=top]:slide-in-from-bottom-2',
}
```

Used like this:

```vue
<PopoverPortal>
  <PopoverContent
    v-bind="{ ...forwarded, ...$attrs }"
    :class="cn('popover-content', ...)"
  />
</PopoverPortal>
```

---

### 💥 Problem

The class `data-[state=open]:animate-in` applies this CSS:

```css
.data-\[state\=open\]\:animate-in[data-state="open"],
[data-\[state\=open\]\:animate-in=""][data-state="open"] {
  animation: una-in;
  animation-name: una-in;
  animation-duration: 150ms;
  --una-enter-opacity: initial;
  --una-enter-scale: initial;
  --una-enter-rotate: initial;
  --una-enter-translate-x: initial;
  --una-enter-translate-y: initial;
}
```

We try to override two variables:

* `data-[state=open]:fade-in-0`:

```css
.data-\[state\=open\]\:fade-in-0[data-state="open"],
[data-\[state\=open\]\:fade-in-0=""][data-state="open"] {
  --una-enter-opacity: 0;
}
```

* `data-[state=open]:zoom-in-95`:

```css
.data-\[state\=open\]\:zoom-in-95[data-state="open"],
[data-\[state\=open\]\:zoom-in-95=""][data-state="open"] {
  --una-enter-scale: 0.95;
}
```

We expect `--una-enter-opacity` and `--una-enter-scale` to be overridden, but they stay as `initial` from `animate-in`.

### 🛠️ To reproduce

-

### 🌈 Expected behavior

Modifiers like `fade-in-0` and `zoom-in-95` should properly override the variables set in `animate-in`, even if both are applied via the same class or shortcut.

### ℹ️ Additional context

I Tried to add `!` before `fade-in-0` and `zoom-in-95` modifiers. It works.

Current animation: 

https://github.com/user-attachments/assets/b279c377-91d7-47d6-a73d-6aa59f6a3d44

Expected animation: 

https://github.com/user-attachments/assets/437f4dd2-19ec-46db-838e-93a847a8e278

### PR DESCRIPTION
**Pull request by phojie**
closes #474 

## Summary by CodeRabbit

* **Style**
  * Updated popover content to use conditional animation and transition effects based on its state and placement, enhancing visual feedback.
  * Simplified default popover styling by removing static animation and transition effects from the preset configuration.
  * Added state- and side-dependent animations to multiple components including combobox, drawer overlay, collapsible content, tooltip, select dropdown, hover card, navigation menu indicator, sheet content, and dialog elements to improve visual transitions.
  * Removed state- and side-dependent animations from preset shortcut styles for combobox, collapsible, drawer, hover card, navigation menu, select, sheet, and tooltip to simplify default styling.
  * Refined dropdown menu components by removing side-dependent slide-in animations while maintaining other state-based animations.
  * Enhanced dropdown menu preset shortcuts with new side-based slide-in animation classes for improved directional feedback.
  * Added fade-in and fade-out animations to the navigation menu viewport for smoother visibility transitions.

### CODE REVIEW

**Comment by mnenie** [comment]
hi @phojie nice catch but I think `data-side` work a we expected in shortcuts and I think that we can keep it in shortcuts
wdyt?

**Comment by phojie** [comment]
> hi @phojie nice catch but I think `data-side` work a we expected in shortcuts and I think that we can keep it in shortcuts wdyt?

oh you mean data-side 😅 yeah, will exclude it

**Comment by mnenie** [comment]
> > hi @phojie nice catch but I think `data-side` work a we expected in shortcuts and I think that we can keep it in shortcuts wdyt?
> 
> Hello @mnenie , I also thought the same case. Please check this issue: #474. I reproduced it, and it doesn’t work properly when data-state is set with Unocss. I believe this is an issue with Unocss, not us.

yea this one for `data-state` only 💯

**Comment by phojie** [comment]
> > > hi @phojie nice catch but I think `data-side` work a we expected in shortcuts and I think that we can keep it in shortcuts wdyt?
> > 
> > 
> > Hello @mnenie , I also thought the same case. Please check this issue: #474. I reproduced it, and it doesn’t work properly when data-state is set with Unocss. I believe this is an issue with Unocss, not us.
> 
> yea this one for `data-state` only 💯

I made the changes brother, needs your review here 🙌🏿

**Comment by mnenie** [comment]
@phojie maybe we should think about custom variant in config with `matcher` that is as if it were force indicated or will it not help ?

**Comment by mnenie** [comment]
I think we can resolve this one but I dont know how haha

File: packages/nuxt/src/runtime/components/hover-card/HoverCardContent.vue [hunk 1]
```diff
@@ -27,6 +27,7 @@ const forwarded = useForwardProps(delegatedProps)
       v-bind="{ ...forwarded, ...$attrs }"
       :class="
         cn(
+          'data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
```
Comment (d-kurchenko) [inline packages/nuxt/src/runtime/components/hover-card/HoverCardContent.vue:30]:
```suggestion
          'data-[state=closed]:animate-out data-[state=open]:animate-in data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95',
```

**Review by mnenie — DISMISSED** [review]

**Review by d-kurchenko — COMMENTED** [review]
The `data-[state=open]:animate-in` is missing, and the `out` animation in the `navigation menu` looks rough, although it might not be directly related to this particular issue. All other components appear to work smoothly.

File: packages/nuxt/src/runtime/components/hover-card/HoverCardContent.vue (hunk 1 above)
Comment (mnenie) [reply packages/nuxt/src/runtime/components/hover-card/HoverCardContent.vue:30]: yea you right, thanks
we have `animate-in` separately earlier

**Comment by mnenie** [comment]
> > I think we can resolve this one but I dont know how haha as to keep everything to the responsibility of `shortcuts`
> 
> How about adding `!`, like `!data-[state=closed]:fade-out-0 !data-[state=closed]:zoom-out-95`? It seems to work as well.

hm let me check 
but maybe I don't think we should use to important in this case 
we should think about `matcher`

**Comment by phojie** [comment]
> @phojie I need your help I think that `navigation-menu` animation is correct haha wdyt ?

what do you mean correct?

**Comment by mnenie** [comment]
> The `data-[state=open]:animate-in` is missing, and the `out` animation in the `navigation menu` looks rough, although it might not be directly related to this particular issue. All other components appear to work smoothly.

@phojie this one about `navigation-menu` out

**Comment by phojie** [comment]
> > The `data-[state=open]:animate-in` is missing, and the `out` animation in the `navigation menu` looks rough, although it might not be directly related to this particular issue. All other components appear to work smoothly.
> 
> @phojie this one about `navigation-menu` out

oh wait. checking..

**Comment by mnenie** [comment]
> > @phojie I need your help I think that `navigation-menu` animation is correct haha wdyt ?
> 
> As for me it disappears abruptly at the end

hmmm so strange

**Comment by phojie** [comment]
> > > > > @phojie I need your help I think that `navigation-menu` animation is correct haha wdyt ?
> > > > 
> > > > 
> > > > As for me it disappears abruptly at the end
> > > 
> > > 
> > > hmmm so strange
> > 
> > 
> > true but even in shadcn-vue this is how animation goes also;
> > ref:
> > [shadcn-vue.com/docs/components/navigation-menu.html](https://www.shadcn-vue.com/docs/components/navigation-menu.html)
> 
> yea that's what I was talking about, I thought @d-kurchenko had a different behavior

feels laggy right? but I think we just have to tune the animation on this one

**Review by mnenie — APPROVED** [review]

**Comment by d-kurchenko** [comment]
https://github.com/una-ui/una-ui/blame/e8b21f599d519de205496a04ae12b0e3b0c8883a/packages/nuxt/src/runtime/components/navigation-menu/NavigationMenuViewport.vue#L33

Adding `data-[state=closed]:fade-out data-[state=open]:fade-in` make `NavigationMenu` smooth. 

I checked all the other components — it looks like the animations are working well everywhere else.

**Review by d-kurchenko — APPROVED** [review]

**Review by mnenie — APPROVED** [review]
